[build]
  publish = "dist"
  command = "npm ci && npm run build:full"

[build.environment]
  NODE_VERSION = "18"
  SITE_URL = "https://rayapp.io"
  NPM_FLAGS = "--prefer-offline --no-audit"

[context.production]
  command = "npm ci --production=false && npm run build:full"
  
[context.deploy-preview]
  command = "npm ci && npm run build:full"
  
[context.branch-deploy]
  command = "npm ci && npm run build:full"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Access-Control-Allow-Origin = "*"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Access-Control-Allow-Origin = "*"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Access-Control-Allow-Origin = "*"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, stale-while-revalidate=86400"
    Access-Control-Allow-Origin = "*"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable, stale-while-revalidate=86400"
    Access-Control-Allow-Origin = "*"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/plain"
    
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"