[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Build plugins for optimization
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.hsforms.net https://grader.rayapp.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-src https://js.hsforms.net https://grader.rayapp.io;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (also defined in _redirects for redundancy)
[[redirects]]
  from = "https://www.rayapp.io/*"
  to = "https://rayapp.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rayrestaurant.com/*"
  to = "https://rayapp.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rayrestaurant.com/*"
  to = "https://rayapp.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://rayrestaurant.com/*"
  to = "https://rayapp.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.rayrestaurant.com/*"
  to = "https://rayapp.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/products"
  to = "/"
  status = 301

[[redirects]]
  from = "/success-stories"
  to = "/case-studies"
  status = 301

[[redirects]]
  from = "/blog"
  to = "https://blogv2.rayapp.io/en/"
  status = 301

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200