'use client'

import React from 'react'
import dynamic from 'next/dynamic'
// Dynamically import CTASection to reduce initial bundle size
const CTASection = dynamic(() => import('../CTASection'), {
  ssr: true,
  loading: () => null,
})
import Link from 'next/link'
import { ArrowLeft, TrendingUp, Star, Eye, Users, Award, MapPin } from 'lucide-react'
import Image from 'next/image'
import { type Locale } from '@/lib/i18n'

const PastaRossaCaseStudy: React.FC<{ locale: Locale }> = ({ locale }) => {
  return (
    <>
      <div className="sr-only">
        <h1>{locale === 'es' ? 'Caso de Estudio Pasta Rossa - 278% de Crecimiento en Reservas para Comer en el Local' : 'Pasta Rossa Case Study - 278% Growth in Dine-In Reservations'}</h1>
      </div>
      <section className="relative min-h-screen bg-gradient-to-br from-red-900 via-rose-900 to-red-900 text-white overflow-hidden">
        <div className="absolute inset-0"><div className="absolute inset-0 bg-gradient-to-br from-red-900 via-rose-800 to-red-900"></div><div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_70%,rgba(225,29,72,0.15),transparent_50%)]"></div><div className="absolute inset-0 opacity-5 bg-[url('data:image/svg+xml,%3Csvg width=%2260%22 height=%2260%22 viewBox=%220 0 60 60%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg fill=%22none%22 fill-rule=%22evenodd%22%3E%3Cg fill=%22%2523ffffff%22 fill-opacity=%220.1%22%3E%3Ccircle cx=%227%22 cy=%227%22 r=%221%22/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')]"></div></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 min-h-screen flex items-center">
          <div className="w-full"><div className="mb-12"><Link href={`/${locale}/case-studies`} className="inline-flex items-center text-rose-200 hover:text-white transition-colors duration-300 text-sm font-medium"><ArrowLeft className="w-4 h-4 mr-2" />{locale === 'es' ? 'Volver a Casos de Estudio' : 'Back to Case Studies'}</Link></div>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center"><div className="space-y-8"><div className="inline-flex items-center px-4 py-2 bg-gradient-to-r from-rose-500/20 to-red-500/20 backdrop-blur-sm rounded-full border border-rose-500/30"><Award className="w-4 h-4 mr-2 text-rose-400" /><span className="text-rose-400 text-sm font-bold uppercase tracking-wider">{locale === 'es' ? 'Historia de Éxito' : 'Success Story'}</span></div>
                <div className="space-y-6"><h1 className="text-4xl sm:text-5xl lg:text-6xl font-black leading-[0.9] tracking-tight">{locale === 'es' ? 'Pasta Rossa Aumenta' : 'Pasta Rossa Increases'}{' '}<span className="text-transparent bg-clip-text bg-gradient-to-r from-rose-400 via-red-400 to-rose-500">{locale === 'es' ? 'Reservas en 278%' : 'Reservations by 278%'}</span>{' '}{locale === 'es' ? 'y' : 'and'}{' '}<span className="text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-emerald-400">{locale === 'es' ? 'Visibilidad Online en 193%' : 'Online Visibility by 193%'}</span></h1>
                  <p className="text-xl text-rose-100 leading-relaxed font-light">{locale === 'es' ? 'Usando el sistema de reservas y SEO local de RAY, Pasta Rossa se convirtió en el destino premier de comida italiana con mesas consistentemente llenas cada noche.' : 'Using RAY\'s reservation system and local SEO, Pasta Rossa became the premier Italian dining destination with consistently full tables every night.'}</p></div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="bg-gradient-to-br from-rose-500/10 to-red-500/10 backdrop-blur-sm rounded-2xl p-6 border border-rose-500/20"><div className="flex items-center justify-center mb-3"><Users className="w-8 h-8 text-rose-400" /></div><div className="text-3xl font-black text-rose-400 mb-1">+278%</div><div className="text-rose-100 text-sm font-medium">{locale === 'es' ? 'Reservas' : 'Reservations'}</div></div>
                  <div className="bg-gradient-to-br from-green-500/10 to-emerald-500/10 backdrop-blur-sm rounded-2xl p-6 border border-green-500/20"><div className="flex items-center justify-center mb-3"><Eye className="w-8 h-8 text-green-400" /></div><div className="text-3xl font-black text-green-400 mb-1">+193%</div><div className="text-rose-100 text-sm font-medium">{locale === 'es' ? 'Visibilidad Online' : 'Online Visibility'}</div></div>
                  <div className="bg-gradient-to-br from-rose-500/10 to-red-500/10 backdrop-blur-sm rounded-2xl p-6 border border-rose-500/20"><div className="flex items-center justify-center mb-3"><Star className="w-8 h-8 text-rose-400 fill-current" /></div><div className="text-3xl font-black text-rose-400 mb-1">4.9★</div><div className="text-rose-100 text-sm font-medium">{locale === 'es' ? 'Calificación Google' : 'Google Rating'}</div></div></div>
              </div>
              <div className="relative"><div className="relative"><div className="absolute -inset-4 bg-gradient-to-r from-rose-500/20 via-red-500/20 to-rose-500/20 rounded-3xl blur-2xl"></div><div className="relative bg-gradient-to-br from-red-950 to-rose-900 rounded-3xl p-8 border border-rose-800"><div className="text-center space-y-6"><div className="text-6xl font-black text-transparent bg-clip-text bg-gradient-to-r from-rose-400 to-red-400">278%</div><div className="text-xl text-rose-100 font-medium">{locale === 'es' ? 'Más Reservas' : 'More Reservations'}</div><div className="text-sm text-rose-300">{locale === 'es' ? 'Siempre completamente reservado' : 'Always fully booked'}</div></div></div></div></div>
            </div>
          </div>
        </div>
        <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce"><div className="w-6 h-10 border-2 border-rose-400 rounded-full flex justify-center"><div className="w-1 h-3 bg-rose-400 rounded-full mt-2 animate-pulse"></div></div></div>
      </section>
      <section className="py-20 bg-gray-900"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="relative rounded-3xl overflow-hidden shadow-2xl"><Image src="/images/success-stories/Pasta-Rossa.webp" alt="Pasta Rossa" width={1200} height={600} className="w-full h-[400px] md:h-[500px] object-cover" sizes="(max-width: 768px) 100vw, 1200px" priority quality={85} placeholder="blur" blurDataURL="data:image/webp;base64,UklGRh4AAABXRUJQVlA4IBIAAAAwAQCdASoBAAEAAwA0JaQAA3AA/vuUAAA=" /><div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent p-8"><p className="text-white text-lg font-medium">{locale === 'es' ? 'Pasta Rossa – pasta italiana auténtica, siempre completamente reservado' : 'Pasta Rossa – authentic Italian pasta, always fully booked'}</p></div></div></div></section>
      <section className="py-20 bg-gray-900"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-4xl mx-auto"><div className="text-center mb-12"><h2 className="text-3xl sm:text-4xl font-black text-white mb-6">{locale === 'es' ? 'El Desafío' : 'The Challenge'}</h2></div><div className="bg-gradient-to-br from-black to-gray-900 rounded-3xl p-8 md:p-12 border border-gray-800"><div className="space-y-6 text-lg text-gray-300 leading-relaxed"><p className="text-xl font-medium text-white">{locale === 'es' ? 'Pasta Rossa tenía mesas vacías a pesar de servir excelente cocina italiana.' : 'Pasta Rossa had empty tables despite serving excellent Italian cuisine.'}</p><p className="font-medium text-white">{locale === 'es' ? 'La auditoría de RAY reveló:' : 'RAY\'s audit revealed:'}</p><ul className="space-y-3 ml-6"><li className="flex items-start"><div className="w-2 h-2 bg-red-400 rounded-full mt-3 mr-4 flex-shrink-0"></div><span>{locale === 'es' ? 'Solo' : 'Only'} <strong className="text-red-400">{locale === 'es' ? '40% de ocupación de mesas' : '40% table occupancy'}</strong> {locale === 'es' ? 'en noches entre semana' : 'on weeknights'}</span></li><li className="flex items-start"><div className="w-2 h-2 bg-red-400 rounded-full mt-3 mr-4 flex-shrink-0"></div><span>{locale === 'es' ? 'Sin sistema de reservas online' : 'No online reservation system'}</span></li><li className="flex items-start"><div className="w-2 h-2 bg-yellow-400 rounded-full mt-3 mr-4 flex-shrink-0"></div><span>{locale === 'es' ? 'El objetivo era' : 'The goal was to'} <strong className="text-green-400">{locale === 'es' ? 'llenar mesas consistentemente' : 'fill tables consistently'}</strong></span></li></ul></div></div></div></div></section>
      <section className="py-20 bg-black"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-4xl mx-auto"><div className="text-center mb-12"><h2 className="text-3xl sm:text-4xl font-black text-white mb-6">{locale === 'es' ? 'La Solución' : 'The Solution'}</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-8"><div className="bg-gradient-to-br from-gray-900 to-black rounded-3xl p-8 border border-gray-800 text-center"><div className="w-16 h-16 bg-gradient-to-br from-rose-500 to-red-500 rounded-2xl flex items-center justify-center mx-auto mb-6"><Users className="w-8 h-8 text-white font-bold" /></div><h3 className="text-xl font-black text-white mb-4">{locale === 'es' ? 'Reservas Online' : 'Online Reservations'}</h3><p className="text-gray-300">{locale === 'es' ? 'Sistema de reservas sin fricciones con confirmaciones automáticas' : 'Seamless booking system with automated confirmations'}</p></div><div className="bg-gradient-to-br from-gray-900 to-black rounded-3xl p-8 border border-gray-800 text-center"><div className="w-16 h-16 bg-gradient-to-br from-green-500 to-emerald-500 rounded-2xl flex items-center justify-center mx-auto mb-6"><MapPin className="w-8 h-8 text-white font-bold" /></div><h3 className="text-xl font-black text-white mb-4">{locale === 'es' ? 'SEO de Cocina Italiana' : 'Italian Cuisine SEO'}</h3><p className="text-gray-300">{locale === 'es' ? 'Optimizado para búsquedas de "restaurante italiano" y "pasta cerca de mí"' : 'Optimized for "Italian restaurant" and "pasta near me" searches'}</p></div><div className="bg-gradient-to-br from-gray-900 to-black rounded-3xl p-8 border border-gray-800 text-center"><div className="w-16 h-16 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-2xl flex items-center justify-center mx-auto mb-6"><Star className="w-8 h-8 text-white font-bold" /></div><h3 className="text-xl font-black text-white mb-4">{locale === 'es' ? 'Generación de Reseñas' : 'Review Generation'}</h3><p className="text-gray-300">{locale === 'es' ? 'Solicitudes automatizadas para construir prueba social' : 'Automated requests to build social proof'}</p></div></div></div></div></section>
      <section className="py-20 bg-gray-900"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-16"><h2 className="text-3xl sm:text-4xl font-black text-white mb-6">{locale === 'es' ? 'Los Resultados' : 'The Results'}</h2></div><div className="max-w-5xl mx-auto"><div className="bg-gradient-to-br from-black to-gray-900 rounded-3xl p-8 md:p-12 mb-12 border border-gray-800"><div className="text-center"><blockquote className="text-2xl md:text-3xl text-white font-medium leading-relaxed mb-8">{locale === 'es' ? '"¡RAY transformó nuestro restaurante! Las reservas aumentaron en ' : '"RAY transformed our restaurant! Reservations increased by '}<span className="text-rose-400 font-black">278%</span>{locale === 'es' ? ', y ahora estamos completamente reservados la mayoría de las noches. La visibilidad online creció en ' : ', and we\'re now fully booked most nights. Online visibility grew by '}<span className="text-green-400 font-black">193%</span>. {locale === 'es' ? 'El sistema de reservas es perfecto y a nuestros clientes les encanta. ¡Nunca hemos estado tan ocupados!"' : 'The reservation system is seamless and our customers love it. We\'ve never been busier!"'}</blockquote><div className="flex items-center justify-center"><div className="text-center"><div className="font-black text-white text-lg">{locale === 'es' ? 'Equipo de Gestión' : 'Management Team'}</div><div className="text-gray-400">Pasta Rossa</div></div></div></div></div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"><div className="bg-gradient-to-br from-rose-500/10 to-red-500/10 backdrop-blur-sm rounded-3xl p-6 border border-rose-500/20 text-center"><div className="flex items-center justify-center mb-4"><div className="w-12 h-12 bg-gradient-to-br from-rose-500 to-red-500 rounded-2xl flex items-center justify-center"><Users className="w-6 h-6 text-white font-bold" /></div></div><div className="text-4xl font-black text-rose-400 mb-2">278%</div><div className="text-white font-medium mb-1">{locale === 'es' ? 'Aumento' : 'Increase'}</div><div className="text-sm text-gray-400">{locale === 'es' ? 'en reservas' : 'in reservations'}</div></div><div className="bg-gradient-to-br from-green-500/10 to-emerald-500/10 backdrop-blur-sm rounded-3xl p-6 border border-green-500/20 text-center"><div className="flex items-center justify-center mb-4"><div className="w-12 h-12 bg-gradient-to-br from-green-500 to-emerald-500 rounded-2xl flex items-center justify-center"><Eye className="w-6 h-6 text-white font-bold" /></div></div><div className="text-4xl font-black text-green-400 mb-2">193%</div><div className="text-white font-medium mb-1">{locale === 'es' ? 'Crecimiento' : 'Growth'}</div><div className="text-sm text-gray-400">{locale === 'es' ? 'en visibilidad' : 'in visibility'}</div></div><div className="bg-gradient-to-br from-rose-500/10 to-red-500/10 backdrop-blur-sm rounded-3xl p-6 border border-rose-500/20 text-center"><div className="flex items-center justify-center mb-4"><div className="w-12 h-12 bg-gradient-to-br from-rose-500 to-red-500 rounded-2xl flex items-center justify-center"><Star className="w-6 h-6 text-white font-bold fill-current" /></div></div><div className="text-4xl font-black text-rose-400 mb-2">4.9★</div><div className="text-white font-medium mb-1">{locale === 'es' ? 'Promedio' : 'Average'}</div><div className="text-sm text-gray-400">{locale === 'es' ? 'calificación Google' : 'Google rating'}</div></div><div className="bg-gradient-to-br from-blue-500/10 to-cyan-500/10 backdrop-blur-sm rounded-3xl p-6 border border-blue-500/20 text-center"><div className="flex items-center justify-center mb-4"><div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-2xl flex items-center justify-center"><TrendingUp className="w-6 h-6 text-white font-bold" /></div></div><div className="text-4xl font-black text-blue-400 mb-2">95%</div><div className="text-white font-medium mb-1">{locale === 'es' ? 'Promedio' : 'Average'}</div><div className="text-sm text-gray-400">{locale === 'es' ? 'ocupación de mesas' : 'table occupancy'}</div></div></div>
            </div></div></section>
      <CTASection locale={locale} />
    </>
  )
}

export default PastaRossaCaseStudy

