import React from 'react'
import { Helmet } from 'react-helmet-async'

const TermsOfService: React.FC = () => {
  return (
    <>
      <Helmet>
        <title>Terms of Service - RAY</title>
        <meta name="description" content="RAY's Terms of Service - Learn about the terms and conditions for using our restaurant marketing platform." />
        <meta name="robots" content="noindex, nofollow" />
        <link rel="canonical" href="https://rayrestaurant.com/terms-of-service" />
      </Helmet>
      
      <div className="py-20 bg-gray-50 min-h-screen">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-xl shadow-lg p-8 md:p-12">
            <h1 className="text-4xl font-bold text-ray-dark-900 mb-8">
              Terms and Conditions of Use of the RAY Platform
            </h1>
            
            <div className="prose prose-lg max-w-none text-ray-dark-700">
              <p className="text-ray-darkGray mb-6">
                <strong>Last updated: May 27th, 2025</strong>
              </p>
              
              <p className="mb-6 leading-relaxed">
                These Terms and Conditions of Use govern access to and use of the www.rayapp.io, www.rayapp.ai and any other website, application, or service operated by BotBit S.A.S., CUIT 30-71580329-8, with its registered office at Av. Gral. Mosconi 2581, Buenos Aires City, Argentina ("RAY" or "we"), including all services offered through the platform ("Services").
              </p>
              
              <p className="mb-6 leading-relaxed">
                By accessing, registering, or using the platform, you ("User" or "you") declare that you have read, understood, and accepted these Terms and Conditions ("Terms") and the Privacy Policy, which is an integral part of this document.
              </p>
              
              <p className="mb-8 leading-relaxed">
                RAY is committed to complying with Argentine Law 25.326 on Personal Data Protection, as well as international regulations applicable to data processing, such as the European Union's General Data Protection Regulation (GDPR), where applicable.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                1. Definitions
              </h2>
              <ul className="list-disc pl-6 mb-6 space-y-2">
                <li><strong>"Platform":</strong> the website www.rayapp.io, www.rayapp.ai and any other website, platform, or application operated by RAY.</li>
                <li><strong>"RAY" or "we":</strong> the company BotBit S.A.S.</li>
                <li><strong>"Client":</strong> any person or entity that accepts these Terms and acquires the Services.</li>
                <li><strong>"Subscription Service":</strong> the RAY Local SEO & Reputation Management service.</li>
                <li><strong>"Services":</strong> includes the Subscription Service and related professional services.</li>
                <li><strong>"Third-party Sites":</strong> any website or external service not operated by RAY.</li>
              </ul>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                2. Acceptance of Terms
              </h2>
              <p className="mb-6 leading-relaxed">
                By contracting the service, the Client fully, expressly, and knowingly accepts these Terms.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                3. Description of Services
              </h2>
              <p className="mb-4 leading-relaxed">
                <strong>3.1.</strong> RAY will provide the Subscription Service and related professional services in accordance with these Terms. Implementation may take between 2 hours and 4 weeks. The Client must actively participate in the process.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>3.2.</strong> RAY is not responsible for the terms, content, or privacy policies of integrated third-party sites or software. The Client accepts their terms (e.g., Google, Facebook, Yelp).
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>3.3.</strong> The Client may display data generated by RAY on their website but must not modify or use them for other purposes without prior written authorization.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>3.4.</strong> The Client agrees to comply with the terms of review platforms and refrain from using them to block reviews or circumvent policies. RAY may suspend the account after 30 days of noncompliance.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>3.5.</strong> The Client is responsible for complying with Resolution 243/2019 ("Do Not Call Registry") and obtaining consent for sending SMS or emails.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>3.6.</strong> The Client must safeguard their credentials and deactivate them if unauthorized access is suspected.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>3.7.</strong> RAY may limit access or apply additional fees if the Client exceeds reasonable usage according to the Fair Use Policy.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>3.8.</strong> The Client agrees to use the Services lawfully. They are responsible for any misuse, including by third parties with access to the Services.
              </p>
              <p className="mb-6 leading-relaxed">
                <strong>3.9.</strong> The Client is solely responsible for any content they publish. RAY is not liable for the use or dissemination of such content by the Client or their users.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                4. Fees and Payment
              </h2>
              <p className="mb-4 leading-relaxed">
                <strong>4.1.</strong> Fees are prepaid and non-refundable. Taxes are not included and are the Client's responsibility. Fee updates will take effect in the next billing cycle with prior notice.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>4.2.</strong> In case of default, RAY may apply late fees, suspend, or terminate the Services without indemnity.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>4.3.</strong> Unless otherwise indicated, Services will automatically renew. Clients must notify cancellation at least 30 days in advance.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>4.4.</strong> Invoices will be sent electronically.
              </p>
              <p className="mb-6 leading-relaxed">
                <strong>4.5.</strong> Cancellation must be requested by email and becomes effective once all outstanding fees are paid.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                5. Intellectual Property Rights
              </h2>
              <p className="mb-4 leading-relaxed">
                <strong>5.1.</strong> RAY retains all intellectual property rights over the Platform and Services. The Client receives a limited, revocable, non-transferable license.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>5.2.</strong> The Client may not copy, modify, or resell the Services without written authorization.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>5.3.</strong> Client Data belongs to the Client, who authorizes RAY to use it as needed for service delivery. RAY and third-party data must be used under these Terms.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>5.4.</strong> Data processing is governed by the Privacy Policy.
              </p>
              <p className="mb-6 leading-relaxed">
                <strong>5.5.</strong> Both parties agree to maintain the confidentiality of information.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                6. Warranties, Limitations, and Indemnity
              </h2>
              <p className="mb-4 leading-relaxed">
                <strong>6.1.</strong> RAY guarantees service provision as described in these Terms.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>6.2.</strong> The Client guarantees they have all necessary consents for service use.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>6.3.</strong> Except as stated in 6.1, all other warranties are excluded.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>6.4.</strong> RAY's liability is limited to the amount paid by the Client in the 12 months prior to the incident. RAY is not liable for indirect damages, data loss, or lost profits.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>6.5.</strong> The Client must indemnify RAY against any claims arising from improper use of the Services.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>6.6.</strong> RAY agrees to defend the Client against third-party IP claims subject to conditions.
              </p>
              <p className="mb-6 leading-relaxed">
                <strong>6.7.</strong> Indemnity obligations are subject to prompt notice, defense control, and cooperation.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                7. Term and Termination
              </h2>
              <p className="mb-4 leading-relaxed">
                <strong>7.1.</strong> These Terms remain in effect while an order form referencing them is active.
              </p>
              <p className="mb-6 leading-relaxed">
                <strong>7.2.</strong> Either party may terminate the agreement for material breach not remedied within 30 days.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                8. Payments
              </h2>
              <p className="mb-6 leading-relaxed">
                RAY uses third-party payment processors (e.g., Increase). The Client agrees to their terms.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                9. Miscellaneous
              </h2>
              <p className="mb-4 leading-relaxed">
                <strong>9.1.</strong> The parties are independent contractors.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>9.2.</strong> RAY may subcontract and is responsible for subcontractors' compliance.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>9.3.</strong> Delay due to force majeure does not constitute breach.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>9.4.</strong> Neither party may assign rights without the other's prior consent, unless provided otherwise herein.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>9.5.</strong> The Client will reimburse reasonable travel expenses related to Professional Services.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>9.6.</strong> Notices will be sent to the contact details provided. The Client's registered email is their official electronic address.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>9.7.</strong> Both parties agree to comply with applicable laws.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>9.8.</strong> These Terms are governed by Argentine law. Any dispute will be submitted to the Ordinary Courts of Buenos Aires City.
              </p>
              <p className="mb-4 leading-relaxed">
                <strong>9.9.</strong> These Terms constitute the entire agreement. Modifications will be notified and effective within 10 days. Continued use constitutes acceptance.
              </p>
              <p className="mb-6 leading-relaxed">
                <strong>9.10.</strong> If any provision is invalid, the remaining provisions will remain in force.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                10. Free Trials
              </h2>
              <p className="mb-6 leading-relaxed">
                RAY may offer free trials subject to specific terms. During such periods, warranties and indemnities do not apply.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                11. International Use
              </h2>
              <p className="mb-6 leading-relaxed">
                Use of the Platform outside Argentina is the Client's sole responsibility. Compliance with local laws is required.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                12. Alternative Dispute Resolution
              </h2>
              <p className="mb-6 leading-relaxed">
                Before taking legal action, the parties will attempt to resolve any dispute through mediation before the Mediation Center of Argentina's Ministry of Justice.
              </p>
              
              <h2 className="text-2xl font-bold text-ray-dark-900 mb-4 mt-8">
                Contact Information
              </h2>
              <p className="leading-relaxed">
                If you have any questions about these Terms of Service, please contact us at{' '}
                <a href="mailto:hello@rayapp.io" className="text-ray-blue hover:underline">
                  hello@rayapp.io
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default TermsOfService