name: Generate and Validate Sitemap

on:
  push:
    branches: [main]
    paths:
      - 'src/app/**'
      - 'public/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  sitemap:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate sitemap
        run: npm run sitemap:generate
        
      - name: Validate sitemap
        run: npm run validate:sitemap
        
      - name: Commit sitemap changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/sitemap.xml
          if git diff --staged --quiet; then
            echo "No changes to sitemap.xml"
          else
            echo "Changes detected in sitemap.xml"
            git commit -m "🤖 Auto-update sitemap.xml [skip ci]"
            git push
          fi
